# name: ci-cd
# on:
#   push:
#     branches:
#       - main

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setups Nodejs
#         uses: actions/setup-node@v4
#         with:
#           node-version: 14

#       - name: Setup depenedncies
#         run: npm install

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: vedady/devops-app:latest

#       - name: deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST}}
#           username: ${{ secrets.USERNAME}}
#           password: ${{ secrets.PASSWORD}}
#           script: |
#             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest
#             docker run -d -p 8080 --name devops-app ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest


name: ci-cd
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Updated to a more recent LTS version

      - name: Install dependencies
        run: npm ci  # Uses package-lock.json for faster, more reliable installs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5  # Updated to v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest
            docker stop devops-app || true
            docker rm devops-app || true
            docker run -d -p 8080:8080 --name devops-app ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest