name: ci-cd

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setups NodeJs
        uses: action/setup-node@v4
        with:
            node-version: 14

      - name: Setup dependencies
        uses: npm install

      - name: build docker image
        uses: docker build -t devops-app .


 